### ISSUE TITLE
How to connect points of different initializations?

### ISSUE THREAD

**Issue by cloudygoose** [timgaripov/dnn-mode-connectivity#1]
Hi,

It's a good paper and thanks for providing the code.
Question:
My understanding is that in the paper checkpoints of two different initializations are connected, but in the code provided it seems it is connecting two checkpoints of the same run of training, that's different, right?

**Comment by timgaripov** [comment]
Hi,

Thank you for interest in our work!

Using the code you can connect weights of any pair of checkpoints of your choice. So if you want to connect checkpoints of different runs, you need to pass the checkpoints collected at the end of each run as --init_start and --init_end arguments of train.py and specify the curve type (--curve=Bezier/PolyChain).

**Comment by cloudygoose** [comment]
Sorry I misunderstand the code! Thanks!
