### ISSUE TITLE
Which code plots distance from the model 

### ISSUE THREAD

**Issue by amitchandak** [timgaripov/dnn-mode-connectivity#3]
Hi,
How do you compute distance of the current model from starting model ? Basically which code generates the plot you have shared in Github page ? Thank you

**Comment by izmailovpavel** [comment]
Hi, we didn't post that code here. However, if you have a pair of models of the same architecture it's easy to compute distance between them:
```python
dist_sq = 0.
for p1, p2 in zip(model.parameters(), initial_model.parameters())
    dist_sq += ((p1 - p2)**2).sum()
dist = torch.sqrt(dist_sq)
```
You just need to save the initial model separately, and then apply this function to compute distance between that and the current model in the end of each epoch.
