### ISSUE TITLE
Name conflict in torchvision versions

### ISSUE THREAD

**Issue by jackonelli** [timgaripov/dnn-mode-connectivity#4]
I ran in to a problem while testing your code. The fix was easy but I thought this could help someone else.

Running the training scheme from your `README` the following error occurs:
```bash
python train.py --dir=train --data_path=data --model=VGG16 --epochs=200 --lr=0.05 --wd=5e-4 --use_test --transform=VGG  
Files already downloaded and verified
You are going to run models on the test set. Are you sure?
Files already downloaded and verified
Traceback (most recent call last):
  File "train.py", line 308, in <module>
    main()
  File "train.py", line 22, in main
    args.transform, args.use_test)
  File "<SRC-ROOT>/data.py", line 79, in loaders
    }, max(train_set.train_labels) + 1
AttributeError: 'CIFAR10' object has no attribute 'train_labels'
```

This is because `torchvision` has changed attribute names.
The latest version `torchvision=0.5.0` only has the attributes `data` and `targets`

**Comment by izmailovpavel** [comment]
Hi @jackonelli, thank you for posting. Yes, there was a change in `torchvision` datasets' interface after this code was released. The fix is to rename the attributes: `train_data` -> `data` and `train_labels` -> `targets`.
