### ISSUE TITLE
How to plot the figure with three model weights?

### ISSUE THREAD

**Issue by ys-zong** [timgaripov/dnn-mode-connectivity#9]
Hi, thanks for the nice work and code!

From the instructions, I can plot the curve of two checkpoints. I'm wondering how to plot the figure with three model weights like the left one in Figure 1 in the paper? Thanks!

**Comment by izmailovpavel** [comment]
Hi @ys-zong, please see [plane.py](https://github.com/timgaripov/dnn-mode-connectivity/blob/master/plane.py) for evaluating the necessary values of the loss and [plane_plot.py](https://github.com/timgaripov/dnn-mode-connectivity/blob/master/plane_plot.py) for making the visualization from these values. See also our [blogpost](https://izmailovpavel.github.io/curves_blogpost/), section "How to Visualize Loss Surfaces?".

**Comment by ys-zong** [comment]
Hi, thanks for your prompt answer! I checked the code and the blog. It's very useful!

So, in my understanding, if I just want to visualize the loss surface of three independently trained models, I don't need to train the curves like [this](https://github.com/timgaripov/dnn-mode-connectivity#training-the-curves). I just need to input three model weights into `plane.py`, and concatenate the parameters of each model [here](https://github.com/timgaripov/dnn-mode-connectivity/blob/77b67db68f3fe20eefddd0ec73275250221ac61f/plane.py#L100). The curve_model defined in the `plane.py` is not necessary in this case? Could you help me check if this is the correct way? Thank you very much! 

I tried to follow this procedure, but during running `plane.py`, the training and testing error are all very large in every grid point (~20-40% error in CIFAR-10), while I can obtain 90%+ accuracy during training the model at first. Got strange figures like this (train loss and testing error)
![image](https://user-images.githubusercontent.com/91270048/181094451-16a6c8f8-fe71-4182-981a-39aba1615b7d.png)
![image](https://user-images.githubusercontent.com/91270048/181094642-a84102d1-f58d-4951-84d5-733bca7a51c6.png)

I'm wondering if there is anything else I need to do besides these procedures? Thanks again!

**Comment by izmailovpavel** [comment]
Hi @ys-zong! Your description of what you are doing seems correct! However, the visualizations look strange. You can try to modify the plane.py code to compute the accuracy  for your `w[i]` points, to ensure that the weights are loading correctly and you are getting good accuracies.

What can happen theoretically, is if your weights are so far apart that the discretization in the visualization is not sufficient to see high-accuracy points. Remember that you are only computing the values of the loss / accuracy on a grid (21x21 by default). 

However, the plots are looking quite strange, so my first guess would be that the models are not loading correctly...

**Comment by ys-zong** [comment]
Thanks for your reply! I've solved it.
